spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: kwon
    password: 9257
  
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      # jpa가 사용하는 기본 넘버링 전략을 사용하지 안는다. 각각의 entity class 에서 정의된 전략 사용
      # @GeneratedValue(strategy = GenerationType.IDENTITY)	
      use-new-id-generator-mappings: false
    properties:
      hibernate.format_sql: true
  
  thymeleaf:
    cache: true
    